rules:
  - id: flask-login-session-protection-app-config-none
    message: Flask-Login provides session protection to help prevent user sessions
      from being stolen. When this is active, sessions will be marked as
      non-fresh when the user's IP or user agent is changed. It is not advised
      to disable this feature.
    severity: INFO
    metadata:
      likelihood: LOW
      impact: MEDIUM
      confidence: HIGH
      category: security
      subcategory:
        - secure default
      cwe:
        - "CWE-613: Insufficient Session Expiration"
      display-name: Insufficient Session Expiration with Flask-Login
      owasp:
        - A02:2017 - Broken Authentication
        - A07:2021 - Identification and Authentication Failures
      references:
        - https://flask-login.readthedocs.io/en/latest/#session-protection
        - https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures
      technology:
        - flask
        - flask-login
      license: Copyright 2023 Semgrep, Inc.
      vulnerability_class:
        - Improper Authorization
    languages:
      - python
    fix: |
      "strong"
    options:
      symbolic_propagation: true
    patterns:
      - patterns:
          - pattern-either:
              - pattern: $APP.config["SESSION_PROTECTION"] = $NONE
              - pattern: $APP.config.SESSION_PROTECTION = $NONE
              - patterns:
                  - pattern: |
                      $APP.config.$UPDATE(
                        ...,
                        SESSION_PROTECTION = $NONE,
                        ...
                      )
                  - pattern-not-inside: |
                      $APP.config.$UPDATE(
                          ...,
                          TESTING=True,
                          ...
                      )
                  - pattern-not-inside: |
                      $APP.config.$UPDATE(
                          ...,
                          DEBUG=True,
                          ...
                      )
                  - metavariable-regex:
                      metavariable: $UPDATE
                      regex: ^(update|from_mapping)$
              - pattern: |
                  $OBJ = $CLASS()
                  ...
                  $OBJ.SESSION_PROTECTION = $NONE
                  ...
                  $APP.config.from_object($OBJ, ...)
              - pattern: |
                  SESSION_PROTECTION = $NONE
                  ...
                  $APP.config.from_object(__name__)
          - metavariable-regex:
              metavariable: $NONE
              regex: ^(None)$
          - focus-metavariable: $NONE
