rules:
  - id: flask-cookie-app-config-samesite-none
    message: "Detected a cookie options with the `SameSite` flag set to \"None\".
      This is a potential security risk that arises from the way web browsers
      manage cookies. In a typical web application, cookies are used to store
      and transmit session-related data between a client and a server. To
      enhance security, cookies can be marked with the \"SameSite\" attribute,
      which restricts their usage based on the origin of the page that set them.
      This attribute can have three values: \"Strict,\" \"Lax,\" or \"None\".
      Make sure that the choice of the `None` value is intentional and that you
      understand the potential security implications. When `SameSite` is set to
      \"Strict\", no 3rd party cookie will be sent with outgoing requests. While
      'Strict' is the most secure option, 'Lax' is a good compromise between
      security and usability and this default value is secure for most
      applications. It is also possible to use the flask-talisman extension to
      enforce a secure configuration."
    severity: INFO
    metadata:
      likelihood: LOW
      impact: LOW
      confidence: HIGH
      category: security
      subcategory:
        - secure default
      cwe:
        - "CWE-1275: Sensitive Cookie with Improper SameSite Attribute"
      display-name: Improper SameSite Attribute in Cookie
      functional-categories:
        - web::search::cookie-config::flask
        - web::search::cookie-config::flask-jwt-extended
        - web::search::cookie-config::flask-login
        - web::search::cookie-config::flask-session
      owasp:
        - A01:2021 - Broken Access Control
      references:
        - https://owasp.org/Top10/A01_2021-Broken_Access_Control
        - https://web.dev/articles/samesite-cookies-explained
      technology:
        - cookie
        - cookies
        - flask
        - web
      license: Copyright 2023 Semgrep, Inc.
      vulnerability_class:
        - Cookie Security
    languages:
      - python
    fix: |
      'Strict'
    options:
      symbolic_propagation: true
    patterns:
      - patterns:
          - pattern-either:
              - pattern: $APP.config["$SESSION_COOKIE_SAMESITE"] = $NONE
              - pattern: $APP.config.$SESSION_COOKIE_SAMESITE = $NONE
              - patterns:
                  - pattern: |
                      $APP.config.$UPDATE(
                        ...,
                        $SESSION_COOKIE_SAMESITE = $NONE,
                        ...
                      )
                  - pattern-not-inside: |
                      $APP.config.$UPDATE(
                          ...,
                          TESTING=True,
                          ...
                      )
                  - pattern-not-inside: |
                      $APP.config.$UPDATE(
                          ...,
                          DEBUG=True,
                          ...
                      )
                  - metavariable-regex:
                      metavariable: $UPDATE
                      regex: ^(update|from_mapping)$
              - pattern: |
                  $OBJ = $CLASS()
                  ...
                  $OBJ.$SESSION_COOKIE_SAMESITE = $NONE
                  ...
                  $APP.config.from_object($OBJ, ...)
              - pattern: |
                  $SESSION_COOKIE_SAMESITE = $NONE
                  ...
                  $APP.config.from_object(__name__)
          - metavariable-regex:
              metavariable: $SESSION_COOKIE_SAMESITE
              regex: ^(SESSION|REMEMBER|JWT)_COOKIE_SAMESITE$
          - metavariable-regex:
              metavariable: $NONE
              regex: ^("None")$
          - focus-metavariable: $NONE
