rules:
  - id: jedis-jedisclientconfig-hardcoded-password
    message: A secret is hard-coded in the application. Secrets stored in source
      code, such as credentials, identifiers, and other types of sensitive data,
      can be leaked and used by internal or external malicious actors. Use
      environment variables to securely provide credentials and other secrets or
      retrieve them from a secure vault or Hardware Security Module (HSM).
    severity: WARNING
    metadata:
      likelihood: HIGH
      impact: MEDIUM
      confidence: HIGH
      interfile: true
      category: security
      subcategory:
        - vuln
      cwe:
        - "CWE-798: Use of Hard-coded Credentials"
      cwe2021-top25: true
      cwe2022-top25: true
      owasp:
        - A07:2021 - Identification and Authentication Failures
      references:
        - https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html
      technology:
        - jedis
        - redis
        - secrets
      license: Copyright 2023 Semgrep, Inc.
      vulnerability_class:
        - Hard-coded Secrets
    languages:
      - java
    pattern-either:
      - patterns:
          - pattern-either:
              - pattern: >
                  redis.clients.jedis.DefaultJedisClientConfig.builder(). ...
                  .password("...")
              - pattern: >
                  (redis.clients.jedis.DefaultJedisClientConfig.Builder $JEDIS).
                  ... .password("...")
              - pattern: >
                  redis.clients.jedis.DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: >
                  new
                  redis.clients.jedis.DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: >
                  (redis.clients.jedis.JedisClientConfig
                  $JEDIS).updatePassword("...")
              - pattern: >
                  (redis.clients.jedis.DefaultJedisClientConfig
                  $JEDIS).updatePassword("...")
          - pattern-not: >
              redis.clients.jedis.DefaultJedisClientConfig.builder(). ...
              .password("")
          - pattern-not: >
              (redis.clients.jedis.DefaultJedisClientConfig.Builder $JEDIS). ...
              .password("")
          - pattern-not: >
              redis.clients.jedis.DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: >
              new
              redis.clients.jedis.DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: |
              (redis.clients.jedis.JedisClientConfig $JEDIS).updatePassword("")
          - pattern-not: >
              (redis.clients.jedis.DefaultJedisClientConfig
              $JEDIS).updatePassword("")
      - patterns:
          - pattern-inside: |
              import redis.clients.jedis.*;
              ...
          - pattern-either:
              - pattern: |
                  DefaultJedisClientConfig.builder(). ... .password("...")
              - pattern: >
                  (DefaultJedisClientConfig.Builder $JEDIS). ... .password("...")
              - pattern: >
                  DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: >
                  new DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: |
                  (JedisClientConfig $JEDIS).updatePassword("...")
              - pattern: |
                  (DefaultJedisClientConfig $JEDIS).updatePassword("...")
          - pattern-not: |
              DefaultJedisClientConfig.builder(). ... .password("")
          - pattern-not: |
              (DefaultJedisClientConfig.Builder $JEDIS). ... .password("")
          - pattern-not: >
              DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: >
              new DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: |
              (JedisClientConfig $JEDIS).updatePassword("")
          - pattern-not: |
              (DefaultJedisClientConfig $JEDIS).updatePassword("")
      - patterns:
          - pattern-inside: |
              import redis.clients.*;
              ...
          - pattern-either:
              - pattern: |
                  jedis.DefaultJedisClientConfig.builder(). ... .password("...")
              - pattern: >
                  (jedis.DefaultJedisClientConfig.Builder $JEDIS). ...
                  .password("...")
              - pattern: >
                  jedis.DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: >
                  new jedis.DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: |
                  (jedis.JedisClientConfig $JEDIS).updatePassword("...")
              - pattern: |
                  (jedis.DefaultJedisClientConfig $JEDIS).updatePassword("...")
          - pattern-not: |
              jedis.DefaultJedisClientConfig.builder(). ... .password("")
          - pattern-not: |
              (jedis.DefaultJedisClientConfig.Builder $JEDIS). ... .password("")
          - pattern-not: >
              jedis.DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: >
              new jedis.DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: |
              (jedis.JedisClientConfig $JEDIS).updatePassword("")
          - pattern-not: |
              (jedis.DefaultJedisClientConfig $JEDIS).updatePassword("")
      - patterns:
          - pattern-inside: |
              import redis.*;
              ...
          - pattern-either:
              - pattern: >
                  clients.jedis.DefaultJedisClientConfig.builder(). ...
                  .password("...")
              - pattern: >
                  (clients.jedis.DefaultJedisClientConfig.Builder $JEDIS). ...
                  .password("...")
              - pattern: >
                  clients.jedis.DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: >
                  new
                  clients.jedis.DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
                  $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "...",
                  ...)
              - pattern: |
                  (clients.jedis.JedisClientConfig $JEDIS).updatePassword("...")
              - pattern: >
                  (clients.jedis.DefaultJedisClientConfig
                  $JEDIS).updatePassword("...")
          - pattern-not: >
              clients.jedis.DefaultJedisClientConfig.builder(). ... .password("")
          - pattern-not: >
              (clients.jedis.DefaultJedisClientConfig.Builder $JEDIS). ...
              .password("")
          - pattern-not: >
              clients.jedis.DefaultJedisClientConfig.create($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: >
              new
              clients.jedis.DefaultJedisClientConfig($CONNECTIONTIMEOUTMILLIS,
              $SOTIMEOUTMILLIS, $BLOCKINGSOCKETTIMEOUTMILLIS, $USER, "", ...)
          - pattern-not: |
              (clients.jedis.JedisClientConfig $JEDIS).updatePassword("")
          - pattern-not: |
              (clients.jedis.DefaultJedisClientConfig $JEDIS).updatePassword("")
